import type { Metadata } from 'next'
import localFont from 'next/font/local'

import PageWrapper from '@/components/layout/PageWrapper'
import Footer from '@/components/widgets/Footer'
import Header from '@/components/widgets/Header'
import '@/styles/main.scss'

export const metadata: Metadata = {
  title: 'Next scss starter kit',
  description: 'Generated by create next app',
}

const myriadPro = localFont({
  src: [
    {
      path: './assets/fonts/MyriadProBold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: './assets/fonts/MyriadProRegular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './assets/fonts/MyriadProLight.woff2',
      weight: '300',
      style: 'normal',
    },
  ],
  variable: '--font-family-base',
  weight: '700',
})

const DMSans = localFont({
  src: [
    {
      path: './assets/fonts/DMSansRegular.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-family-accent',
  weight: '400',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="page">
      <body className={`${myriadPro.variable} ${DMSans.variable} page__body`}>
        <PageWrapper>
          <Header />
          <main className="page__main">{children}</main>
          <Footer />
        </PageWrapper>
      </body>
    </html>
  )
}
